# -*- coding: utf-8 -*-
"""Lab1b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nIDx2etNneHQQFP2qoUnkClOKMPgyVJc
"""

students = []
courses = []
marks = {}

def input_students():
    n = int(input("Enter number of students: "))
    for _ in range(n):
        sid = input("Student ID: ")
        name = input("Student name: ")
        dob = input("Date of birth (dd/mm/yyyy): ")
        students.append({"id": sid, "name": name, "dob": dob})

def input_courses():
    n = int(input("Enter number of courses: "))
    for _ in range(n):
        cid = input("Course ID: ")
        name = input("Course name: ")
        courses.append({"id": cid, "name": name})

def input_marks():
    course_id = input("Enter course ID to input marks: ")
    if course_id not in [c["id"] for c in courses]:
        print("Course not found!")
        return
    if course_id not in marks:
        marks[course_id] = {}
    for student in students:
        mark = float(input(f"Enter mark for {student['name']} (ID: {student['id']}): "))
        marks[course_id][student["id"]] = mark

# Listing Functions
def list_students():
    print("\n--- Students ---")
    for s in students:
        print(f"ID: {s['id']}, Name: {s['name']}, DoB: {s['dob']}")

def list_courses():
    print("\n--- Courses ---")
    for c in courses:
        print(f"ID: {c['id']}, Name: {c['name']}")

def show_marks():
    course_id = input("Enter course ID to show marks: ")
    if course_id not in marks:
        print("No marks recorded for this course.")
        return
    print(f"\n--- Marks for course {course_id} ---")
    for sid, mark in marks[course_id].items():
        student = next(s for s in students if s["id"] == sid)
        print(f"{student['name']} (ID: {sid}): {mark}")

def main():
    while True:
        print("\n--- Student Mark Management ---")
        print("1. Input students")
        print("2. Input courses")
        print("3. Input marks")
        print("4. List students")
        print("5. List courses")
        print("6. Show marks")
        print("0. Exit")

        choice = input("Choose an option: ")
        if choice == "1":
            input_students()
        elif choice == "2":
            input_courses()
        elif choice == "3":
            input_marks()
        elif choice == "4":
            list_students()
        elif choice == "5":
            list_courses()
        elif choice == "6":
            show_marks()
        elif choice == "0":
            break
        else:
            print("Invalid choice!")

if __name__ == "__main__":
    main()