# -*- coding: utf-8 -*-
"""Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxSpoFxURVDEm4lISNbraC8p2_7c_5Ii
"""

#Exercise 1

import math

radius = float(input("Enter circle radius? "))
area = math.3.14 * radius**2
print("Circle area = ", area)

#Exercise 2

celsius = float(input("Enter the temperature in Celsius? "))
fahrenheit = (celsius * 9 / 5) + 32

c_str = int(celsius) if celsius.is_integer() else celsius
print(f"{c_str} (C) = {fahrenheit:.1f} (F)")

#Exercise 3

num = int(input("Enter a number? "))

is_prime = True
if num < 2:
    is_prime = False
else:
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            is_prime = False
            break

if is_prime:
    print(f"{num} is a prime number")
else:
    print(f"{num} is a NOT prime number")

#Exercise 4

number = int(input("Enter a number? "))

if number <= 0:
    print(f"{number} is a NOT perfect number")
else:
    divisor_sum = sum(i for i in range(1, number) if num % i == 0)
    if divisor_sum == number:
        print(f"{number} is a perfect number")
    else:
        print(f"{number} is a NOT perfect number")

#Exercise 5

colors = ["blue", "yellow", "black", "red", "white"]  # Example list with "Red" at index 3

user_color = input("What is your favorite color? ")

found = False
for index, color in enumerate(colors):
    if color.lower() == user_color.strip().lower():

        print(f"Your colod is at index {index} in my list")
        found = True
        break

if not found:
    print("Sorry, I could not find your color")

#Exercise 6

# range1: 0, 1, 2, 3, 4, 5, 6
range1 = list(range(7))
print("range1", lispt(range1))

# range2: 1, 4, 7, 10
range2 = list(range(1, 11, 3))
print("range2", list(range2))

# range3: 5, 4, 3, 2, 1
range3 = list(range(5, 0, -1))
print("range3", list(range3))

# range4: 6, 4, 2, 0, -2
range4 = list(range(6, -3, -2))
print("range4", list(range4))

#Exercise 7

def remove_dollar_sign(s):
    return s.replace("$", "")

print(remove_dollar_sign("$100,000$ USD"))

#Exercise 8

def extract_even(l):
    return [x for x in l if x % 2 == 0]

print(extract_even([1, 4, 5, -1, 10]))

#Exercise 9:

def factorial(n):
    if n < 0:
        return None
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result
print(factorial(5))